version:  "3.9"

services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
    - todolist_pg_data_14:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 2s
      retries: 10

  run_migrations:
    image: ${DOCKERHUB_USERNAME}/diploma2:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  collect_static:
    image: ${DOCKERHUB_USERNAME}/diploma2:latest
    env_file: .env
    command: python manage.py collectstatic - c --no-input
    volumes:
      - django_static:/opt/app/static/

  api:
    image: ${DOCKERHUB_USERNAME}/diploma2:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully

  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/


volumes:
  todolist_pg_data_14:
  django_static: